Adding unit tests and other support for not writing default extent (#68)
sandflow/ttconv pull request #125
Opened 2020-11-11 21:33 UTC by BobBrownConsulting

2020-11-13 00:08 UTC, BobBrownConsulting commented
I should probably add more unit tests. Thoughts @palemieux

2020-11-16 04:18 UTC, palemieux requested changes

2020-11-16 04:18 UTC, palemieux commented on src/main/python/ttconv/imsc/style_properties.py
> +      if attrib_value == styles.SpecialValues.none:
```suggestion
      if attrib_value is not styles.SpecialValues.none:
```

2020-11-18 23:40 UTC, palemieux approved these changes

2020-11-18 23:44 UTC, BobBrownConsulting commented
Implementing filtering of Extent when StyleProperites do not have a value with px.
Closes #68

2020-11-18 23:44 UTC, merged