First stl-reader tests based on IRT SCF tests
sandflow/ttconv pull request #263
Opened 2021-08-03 16:19 UTC by xchange11

- Some of the test files of the IRT SCF STLXML2EBU-TT module have been used.
- The STLXML files have been translated to binary stl files.
- Assertions have been adopted for the ttconv stl-reader.

2021-08-04 03:34 UTC, palemieux requested changes

2021-08-04 03:34 UTC, palemieux commented on src/test/python/test_stl_reader.py
> +      self.assertEqual(p.get_begin(),\
```suggestion
      self.assertEqual(p.get_begin(),
```

No need for `\` at the end of a line.

2021-08-04 06:25 UTC, xchange11 commented on src/test/python/test_stl_reader.py
> +      self.assertEqual(p.get_begin(),\
True! Thanks!

2021-08-06 13:12 UTC, xchange11 commented
Close this PR in favor of PR #264

2021-08-06 13:12 UTC, closed without merging