SCC: support word repetition for normal and extended characters
sandflow/ttconv pull request #392
Opened 2023-07-27 15:52 UTC by humberthardy

I notice that some characters are skipped due to SCC_word repetition. 

Here are some examples: 
- SCC word "em": `remember` is (sometimes) translated in `rember`
- SCC word "ti": `repetition` can be translated in `repetion`
...

PS: My knowledge about SCC is low, I might miss something :)

2023-07-27 18:09 UTC, palemieux commented
Thanks for the report. Will process shortly. I have opened dedicated issue #393 .

2023-07-29 17:13 UTC, palemieux requested changes

2023-07-29 17:13 UTC, palemieux commented on src/main/python/ttconv/scc/reader.py
> +      if self.previous_code == scc_word.value and self.previous_code_type is not str:
I am thinking we should add a `isControlCode()` in `SccWord`, which would test whether the MSB is a control character.

2023-07-29 17:39 UTC, palemieux commented on src/main/python/ttconv/scc/reader.py
> +      if self.previous_code == scc_word.value and self.previous_code_type is not str:
@humberthardy Should I propose an update to your branch?

2023-07-31 17:51 UTC, palemieux approved these changes

2023-08-08 15:33 UTC, valnoel requested changes
A blank line missing at the end of the word.py file.

Otherwise, it looks OK to me!

2023-08-12 20:39 UTC, merged